### ISSUE TITLE
Sample extension's About page errors

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/sample-extension#17]
The About page for the sample extension fails to render.

### To Reproduce
1. Go to http://127.0.0.1:3333/extension/sample/

### Current Results

(From new Butterfly error page for improve readability)

<h2 style="color: rgb(0, 0, 0); font-family: Times; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">HTTP ERROR 500 Butterfly Error Butterfly caught the following error while processing the request:</h2>
URI: | /extension/sample/
-- | --
500
Butterfly Error Butterfly caught the following error while processing the request:
refine
org.mozilla.javascript.EcmaError: TypeError: Cannot call property stringArrayLength in object [JavaPackage com.google.refine.sampleExtension.SampleUtil]. It is not a function, it is "object". (file:/Users/tfmorris/git/OpenRefine2/main/webapp/../../extensions/sample/module/MOD-INF/controller.js#75)

<h3 style="color: rgb(0, 0, 0); font-family: Times; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Caused by:</h3><pre style="color: rgb(0, 0, 0); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">org.mozilla.javascript.EcmaError: TypeError: Cannot call property stringArrayLength in object [JavaPackage com.google.refine.sampleExtension.SampleUtil]. It is not a function, it is "object". (file:/Users/tfmorris/git/OpenRefine2/main/webapp/../../extensions/sample/module/MOD-INF/controller.js#75)
	at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:4563)
	at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:4544)
	at org.mozilla.javascript.ScriptRuntime.typeError(ScriptRuntime.java:4576)
	at org.mozilla.javascript.ScriptRuntime.typeErrorById(ScriptRuntime.java:4581)
	at org.mozilla.javascript.ScriptRuntime.notFunctionError(ScriptRuntime.java:4662)
	at org.mozilla.javascript.ScriptRuntime.getPropFunctionAndThisHelper(ScriptRuntime.java:2585)
	at org.mozilla.javascript.ScriptRuntime.getPropFunctionAndThis(ScriptRuntime.java:2568)
	at org.mozilla.javascript.gen.file__Users_tfmorris_git_OpenRefine2_main_webapp_______extensions_sample_module_MOD_INF_controller_js_18._c_process_2(file:/Users/tfmorris/git/OpenRefine2/main/webapp/../../extensions/sample/module/MOD-INF/controller.js:75)
	at org.mozilla.javascript.gen.file__Users_tfmorris_git_OpenRefine2_main_webapp_______extensions_sample_module_MOD_INF_controller_js_18.call(file:/Users/tfmorris/git/OpenRefine2/main/webapp/../../extensions/sample/module/MOD-INF/controller.js)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:380)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3868)
	at org.mozilla.javascript.gen.file__Users_tfmorris_git_OpenRefine2_main_webapp_______extensions_sample_module_MOD_INF_controller_js_18.call(file:/Users/tfmorris/git/OpenRefine2/main/webapp/../../extensions/sample/module/MOD-INF/controller.js)
	at edu.mit.simile.butterfly.ButterflyModuleImpl$Controller.process(ButterflyModuleImpl.java:399)
	at edu.mit.simile.butterfly.ButterflyModuleImpl$Controller.run(ButterflyModuleImpl.java:377)
	at org.mozilla.javascript.Context.call(Context.java:535)
	at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:472)
	at edu.mit.simile.butterfly.ButterflyModuleImpl.processScript(ButterflyModuleImpl.java:654)
	at edu.mit.simile.butterfly.ButterflyModuleImpl.process(ButterflyModuleImpl.java:427)
	at edu.mit.simile.butterfly.Butterfly.service(Butterfly.java:524)
	at com.google.refine.RefineServlet.service(RefineServlet.java:217)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:750)</pre>

### Expected Behavior

Velocity template renders correctly.

### Versions
 - OpenRefine: 3.7 and current HEAD of master (not sure how far back it goes)

### Additional context

At first glance it looks like perhaps the `SampleUtil` class isn't getting compiled or packaged in the right place.

**Comment by tfmorris** [comment]
Not sure if this is still a problem, but transferring the issue from the main repo to the new one for verification.

**Comment by tfmorris** [comment]
It looks like there is still a problem with this page, but it's changed slightly. As currently configured, the new URL is 

http://127.0.0.1:3333/extension/my-sample-extension/

(but should probably change to http://127.0.0.1:3333/extension/openrefine-sample-extension/)

The page doesn't error now, but also doesn't resolve template variables, so it outputs:

> Here is someString: $someString, and someInt: $someInt
